Enhancement for non-priveleged users. Can specify arbitrary namespace… (#25)
Enhancement for non-priveleged users. Can specify arbitrary namespace in which to do image builds

diff --git a/cicd/pipeline b/cicd/pipeline
--- a/cicd/pipeline
+++ b/cicd/pipeline
@@ -1,4 +1,5 @@
 #!/bin/bash
+IMAGE_NAMESPACE=openshift
 
 deploy() {
   app_name=${1}
@@ -6,14 +7,12 @@ deploy() {
 
   echo "Creating a pipeline for ${app_name} application..."
   if [ ${deploy_templates} -eq 1 ]; then
-    oc process -f jenkins-slaves/templates/jenkins-slave-image-mgmt-template.json \
-      | oc create -f - -n openshift
-    oc process -f cicd/jenkins-s2i/jenkins-s2i.yml \
+    create_or_update_from_template jenkins-slaves/templates/jenkins-slave-image-mgmt-template.json
+    create_or_update_from_template cicd/jenkins-s2i/jenkins-s2i.yml \
       -v JENKINS_GIT_URL=https://github.com/redhat-cop/containers-quickstarts.git \
-      -v JENKINS_GIT_CONTEXT_DIR=cicd/jenkins-s2i \
-      | oc create -f - -n openshift
-    oc create -f cicd/pipeline-basic/generic-java-jenkins-pipeline.yml -n openshift
-    oc create -f cicd/pipeline-basic/jws30-tomcat8-deployment.yml -n openshift
+      -v JENKINS_GIT_CONTEXT_DIR=cicd/jenkins-s2i
+    create_or_update_template cicd/pipeline-basic/generic-java-jenkins-pipeline.yml
+    create_or_update_template cicd/pipeline-basic/jws30-tomcat8-deployment.yml
   else
     echo "skipping template deployment"
   fi
@@ -28,18 +27,38 @@ deploy() {
   oc policy add-role-to-user edit system:serviceaccount:${app_name}-dev:jenkins -n ${app_name}-prod
 
   # Create jenkins master
-  oc new-app --template=jenkins-ephemeral -p JENKINS_IMAGE_STREAM_TAG=jenkins2-s2i:latest -n ${app_name}-dev
+  oc new-app --template=jenkins-ephemeral -p JENKINS_IMAGE_STREAM_TAG=jenkins2-s2i:latest -p NAMESPACE=${IMAGE_NAMESPACE} -n ${app_name}-dev
 
   # Create application deployments
-  oc new-app --template=jws30-tomcat8-deployment -p APPLICATION_NAME=${app_name} -n ${app_name}-dev
-  oc new-app --template=jws30-tomcat8-deployment -p APPLICATION_NAME=${app_name} -n ${app_name}-stage
-  oc new-app --template=jws30-tomcat8-deployment -p APPLICATION_NAME=${app_name} -n ${app_name}-prod
+  oc new-app --template=${IMAGE_NAMESPACE}/jws30-tomcat8-deployment -p APPLICATION_NAME=${app_name} -n ${app_name}-dev
+  oc new-app --template=${IMAGE_NAMESPACE}/jws30-tomcat8-deployment -p APPLICATION_NAME=${app_name} -n ${app_name}-stage
+  oc new-app --template=${IMAGE_NAMESPACE}/jws30-tomcat8-deployment -p APPLICATION_NAME=${app_name} -n ${app_name}-prod
 
   # Instantiate pipeline
-  oc new-app --template=generic-java-jenkins-pipeline -p APPLICATION_NAME=${app_name} -n ${app_name}-dev
+  oc new-app --template=${IMAGE_NAMESPACE}/generic-java-jenkins-pipeline -p APPLICATION_NAME=${app_name} -n ${app_name}-dev
 
   echo "Done!"
 
+}
+
+create_or_update_from_template() {
+  # For each of our templates we're going to first, attempt to create it, and if that fails, we'll replace it
+  template=${1}
+  shift
+  args=${@}
+  oc process -f ${template} ${args} \
+    | oc create -f - -n ${IMAGE_NAMESPACE} 2>/dev/null \
+    || oc process -f ${template} ${args} \
+    | oc replace -f- -n ${IMAGE_NAMESPACE}
+}
+
+create_or_update_template() {
+  # For each of our templates we're going to first, attempt to create it, and if that fails, we'll replace it
+  template=${1}
+  shift
+  args=${@}
+  oc create -f ${template} -n ${IMAGE_NAMESPACE} 2>/dev/null \
+    || oc replace -f ${template} -n ${IMAGE_NAMESPACE}
 }
 
 cleanup() {
@@ -49,11 +68,32 @@ cleanup() {
 }
 
 if [ "$(basename $PWD)" != "containers-quickstarts" ]; then
-  echo "You must be in the `containers-quickstarts` directory to run this script."
+  echo "You must be in the 'containers-quickstarts' directory to run this script."
   exit 1
 fi
 
 method=${1}
-app_name=${2}
+shift
+app_name=${1}
+shift
+
+
+while [[ $# -gt 1 ]]
+do
+  key="$1"
+
+  case $key in
+      -i|--image-namespace)
+      IMAGE_NAMESPACE="$2"
+      shift # past argument
+      ;;
+      *)
+        # unknown option
+        echo "Unknown option"
+        exit 1
+      ;;
+  esac
+  shift # past argument or value
+done
 
 ${method} ${app_name}
